config/routes.rb
Rails.application.routes.draw do
  resource  :profile,     only: [ :show, :update ]
  resources :users,       only: [ :index, :show ]
  resources :judges,      only: [ :index, :show, :new, :create ]
  resources :categories,  only: [ :show ]

  resources :problems, only: [ :index, :show, :new, :create ] do
    resources :solutions, only: [ :new, :create, :edit, :update ]
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy', as: :logout
  get '/regwall', to: 'welcome#regwall', as: :regwall
  get '/.well-known/acme-challenge/:id', to: 'welcome#letsencrypt'
  root 'welcome#index'
end

app/models/judge.rb
class Judge < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  default_scope { order(:name) }

  has_many :problems

  validates :name, presence: true, uniqueness: true
  validates :url, presence: true

  delegate :count, to: :problems, prefix: true

  def to_s
    name
  end
end

app/controllers/judges_controller.rb
class JudgesController < ApplicationController
  before_action :require_login!, except: [ :index, :show ]

  def index
    @judges = Judge.page(page)
  end

  def show
    @judge = Judge.friendly.find(params[:id])
    @problems = filter_problems(@judge.problems)
  end

  def new
    @judge = Judge.new
  end

  def create
    @judge = Judge.new(judge_params)
    if @judge.save
      track_event('Judge Created', @judge.as_json)
      redirect_to @judge, notice: I18n.t("judges.create.success")
    else
      flash.now[:alert] = I18n.t("judges.create.error")
      render :new
    end
  end

  private

  def judge_params
    params.require(:judge).permit(:name, :url)
  end
end

app/helpers/judges_helper.rb
module JudgesHelper
  def website_link_for(judge, options = {})
    options = {
      title: t('.go_to_website', name: judge.name),
      target: '_blank',
    }.merge(options)

    link_to judge.url, options do
      icon 'globe', t('.website')
    end
  end
end

app/views/judges/_judge.html.erb
<%= div_for judge do %>
  <h5>
    <%= link_to judge.name, judge %>
    <span class='links'>( <%= website_link_for judge %> )</span>
  </h5>

  <div class='info'><%= pluralize judge.problems_count, I18n.t('problem') %></div>
<% end %>

app/views/judges/index.html.erb
<h1 class='title'><%= t('.title') %></h1>

<div class='subtitle'>
  <% if logged_in? %>
    <%= link_to t('.add_judge'), new_judge_path %>
  <% else %>
    <%= raw t('.guest_add_judge', login: link_to(t('.login_text'), login_path(:github))) %>
  <% end %>
</div>

<div class='judges'><%= render @judges %></div>
<%= paginate @judges %>

app/views/judges/new.html.erb
<h1 class='title'><%= t('.title') %></h1>

<%= simple_form_for @judge do |f| %>
  <%= f.input :name, placeholder: "Cómo Vamos Judge" %>
  <%= f.input :url, as: :url, placeholder: "https://judge.comovamos.co" %>
  <%= f.button :submit, data: {"disable-with" => t('application.processing')} %>
<% end %>

app/views/judges/show.html.erb
<h1 class='title'><%= @judge.name %></h1>

<p>These are the problems from <%= @judge.name %>.</p>

<%= render 'problems/problems', problems: @problems %>