config/routes.rb
Rails.application.routes.draw do
  resource  :profile,     only: [ :show, :update ]
  resources :users,       only: [ :index, :show ]
  resources :judges,      only: [ :index, :show, :new, :create ]
  resources :categories,  only: [ :show ]

  resources :problems, only: [ :index, :show, :new, :create ] do
    resources :solutions, only: [ :new, :create, :edit, :update ]
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy', as: :logout
  get '/regwall', to: 'welcome#regwall', as: :regwall
  get '/.well-known/acme-challenge/:id', to: 'welcome#letsencrypt'
  root 'welcome#index'
end

app/models/problem.rb
class Problem < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  DIFFICULTY_MAP = {
    0 => I18n.t("problems.difficulties.easy"),
    1 => I18n.t("problems.difficulties.moderate"),
    2 => I18n.t("problems.difficulties.difficult"),
    3 => I18n.t("problems.difficulties.expert"),
  }

  belongs_to :judge, counter_cache: true
  belongs_to :creator, class_name: "User"

  has_many :categorizations
  has_many :categories, through: :categorizations
  has_many :solutions

  validates :title, :url, :judge_id, presence: true
  validates :number, presence: true, uniqueness: { scope: :judge_id }
  validates :difficulty_level, numericality: { only_integer: true }, inclusion: { in: DIFFICULTY_MAP.keys }, presence: true

  delegate :name, to: :judge, prefix: true

  def name
    "#{number} - #{title}"
  end

  def difficulty
    DIFFICULTY_MAP[difficulty_level]
  end

  def to_s
    title
  end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  before_action :require_login!, except: [ :index, :show ]

  def index
    @problems = filter_problems(Problem.order('updated_at DESC'))
  end

  def show
    @problem = Problem.friendly.find(params[:id])
    @solutions = @problem.solutions.includes(:user)
  end

  def new
    @problem = Problem.new
  end

  def create
    @problem = current_user.problems.new(problem_params)
    if @problem.save
      track_event('Problem Created', @problem.as_json)
      redirect_to @problem, notice: I18n.t('problems.create.success')
    else
      flash.now[:alert] = I18n.t("problems.create.error")
      render :new
    end
  end

  private

  def problem_params
    permitted_args = [
      :difficulty_level, :judge_id, :url, :title, :number, { category_ids: [ ] }
    ]
    params.require(:problem).permit(permitted_args)
  end
end

app/helpers/problems_helper.rb
module ProblemsHelper
  def without_problems
    unless controller.controller_name =~ /users/
      default_no_problems_text
    end
  end

  def default_no_problems_text
    add_link = link_to t('.add_link'), new_problem_path
    t('.no_problems', add_link: add_link).html_safe
  end
end

app/views/problems/_problem.html.erb
<%= div_for problem do %>
  <h5>
    <%= link_to problem.name, problem %>
    <span class='small'>
      (<%= pluralize problem.solutions_count, t("problems.show.solution") %>)
    </span>
  </h5>

  <div>
    <div class='meta'><strong>Judge:</strong> <%= link_to problem.judge_name, problem.judge %></div>
    <div class='meta'><strong>Solutions:</strong> <%= problem.solutions_count%></div>
    <div class='meta'><strong>Difficulty:</strong> <%= link_to problem.difficulty, url_for(level: problem.difficulty_level) %></div>
  </div>

  <div class='categories'>
    <% problem.categories.each do |category| %>
      <%= category_badge(category) %>
    <% end %>
  </div>
<% end %>

app/views/problems/_problems.html.erb
<section class='problems'>
  <% if problems.any? %>
    <%= render problems %>

    <%= paginate problems %>
  <% else%>
    <%= without_problems %>
  <% end %>
</section>

app/views/problems/index.html.erb
<h1 class='title'><%= t('.title') %></h1>
<div class='subtitle'>
  <% if logged_in? %>
    <%= link_to t('.add'), new_problem_path %>
  <% else %>
    <%= raw t('.guest_add', login: link_to(t('.login_text'), login_path(:github))) %>
  <% end %>
</div>

<%= render 'problems/problems', problems: @problems %>

app/views/problems/new.html.erb
<h1 class='title'><%= t('.title') %></h1>

<%= simple_form_for @problem do |f| %>
  <%= f.input :judge_id, collection: Judge.all, label_method: :name, value_method: :id, prompt: t('.select_judge'), input_html: chosen_options(size: 150) %>
  <%= f.input :number, placeholder: "100", hint: t('.number_hint') %>
  <%= f.input :title,  placeholder: "3n + 1", hint: t('.title_hint') %>
  <%= f.input :url,    placeholder: "http://example.com/problem/3n-plus-1.html" %>
  <%= f.input :difficulty_level, collection: Problem::DIFFICULTY_MAP.invert.to_a, input_html: chosen_options %>
  <%= f.association :categories, collection: sidebar_categories, input_html: chosen_options %>
  <%= f.button :submit, data: {"disable-with" => t('application.processing')} %>
<% end %>

app/views/problems/show.html.erb
<h1 class='title'>
  <%= @problem.name %>
  <span class='x-small'>&nbsp; (<%= pluralize(@problem.solutions_count, t('.solution')) %>)</span>
</h1>

<div class='subtitle'>
  <%= link_to new_problem_solution_path(@problem) do %>
    <%= icon 'plus', t('.add_solution') %>
  <% end %>

  <%= link_to @problem.url, target: '_blank' do %>
    <%= icon 'globe', t('.website') %>
  <% end %>
</div>

<div class='solutions'>
  <%= render @solutions %>
</div>