config/routes.rb
Rails.application.routes.draw do
  resource  :profile,     only: [ :show, :update ]
  resources :users,       only: [ :index, :show ]
  resources :judges,      only: [ :index, :show, :new, :create ]
  resources :categories,  only: [ :show ]

  resources :problems, only: [ :index, :show, :new, :create ] do
    resources :solutions, only: [ :new, :create, :edit, :update ]
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy', as: :logout
  get '/regwall', to: 'welcome#regwall', as: :regwall
  get '/.well-known/acme-challenge/:id', to: 'welcome#letsencrypt'
  root 'welcome#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def filter_problems(problems)
    problems = problems.where(difficulty_level: params[:level]) if params[:level]
    problems.page(page)
  end

  helper_method def page
    [params[:page].to_i, 1].max
  end

  helper_method def full_layout?
    !!@full_layout
  end

  def login_user!(user)
    logout_user!
    Analytics.identify(
      user_id: user.id,
      traits: {
        username: user.username,
        name: user.name,
        registered_on: user.created_at,
      }
    )
    session[:user_id] = user.id
    track_event('Logged In', user.as_json)
  end

  def logout_user!
    track_event('Logged Out', current_user.as_json)
    @current_user = session[:user_id] = nil
  end

  helper_method def current_user
    @current_user ||= begin
      if session[:user_id]
        User.find(session[:user_id])
      else
        User.new
      end
    end
  end

  helper_method def logged_in?
    current_user.persisted?
  end

  def require_not_logged_in!
    if logged_in? && !params[:force]
      redirect_to root_url and return
    end
  end

  def require_login!
    if !logged_in? || params[:force]
      session[:return_to] = request.original_fullpath
      redirect_to root_url, alert: I18n.t("application.login_required") and return
    end
  end

  def redirect_back_or_to(url = root_url, options = {})
    redirect_url = session.delete(:return_to) || url
    redirect_to redirect_url, options
  end

  def track_event(event, data = {})
    return unless logged_in?
    Analytics.track(
      user_id: current_user.id,
      event: event,
      properties: data
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def localized_key(key)
    "#{I18n.locale}/#{key}".freeze
  end

  def content_or_partial(content, partial = nil)
    partial ||= content
    content_for?(content) ? content_for(content) : render(content.to_s)
  end

  def login_path(provider = :github)
    "/auth/#{provider}".freeze
  end

  def sidebar_categories
    @sidebar_categories ||= Category.all
  end
end

app/views/application/_alerts.html.erb
<div class='alerts'>
  <% if notice %> <div class='alert success'><%= notice.html_safe %></div> <% end %>
  <% if alert %>  <div class='alert error'> <%= alert.html_safe %> </div> <% end %>
</div>

app/views/application/_complete_profile.html.erb
<% unless current_page?(profile_path) %>
    <% if current_user.persisted? && !current_user.profile_ready? %>
      <div class='info alert notice'>
        <% profile_link = link_to(t('.here'), profile_path) %>
        <%= t('.complete_profile', profile_link: profile_link).html_safe %>
      </div>
    <% end %>
<% end %>

app/views/application/_footer.html.erb
<footer>
  <%= link_to 'https://github.com/nhocki/como_vamos', target: '_blank' do %>
    <%= t('.open_source') %>
  <% end %>
  <div class='author'>
    <%= link_to "Rebuilt by Nicolás Hock Isaza", 'http://blog.nhocki.com', target: '_blank' %>
  </div>
</footer>

app/views/application/_header.html.erb
<nav class='top'>
  <div class='wrapper'>
    <ul class='main'>
      <li><%= nav_link "¿Cómo Vamos?", root_path %></li>
      <li><%= nav_link t(".problems"), problems_path %></li>
      <li><%= nav_link t(".judges"), judges_path %></li>
      <li><%= nav_link t(".users"), users_path %></li>
    </ul>

    <h6 class='session'>
      <% if logged_in? %>
        <div>
          <%= t('.logged_in_as') %>
          <%= link_to current_user.to_s, profile_path, class: 'edit-profile' %>

          <span class='small logout'>
            (<%= link_to t('.logout'), logout_path %>)
          </span>
        </div>
      <% else %>
        <%= t('.signin_with') %>
        <%= link_to "GitHub", login_path(:github) %>
      <% end %>
    </h6>
  </div>
</nav>

app/views/application/_sidebar.html.erb
<section class='sidebar'>
  <h3><%= t('.categories') %></h3>

  <ul>
    <% sidebar_categories.each do |category| %>
      <%= content_tag_for(:li, category) do %>
        <%= nav_link category.name.titleize, category %>
      <% end %>
    <% end %>
  </ul>
</section>

app/views/application/_tracking.html.erb
<script type="text/javascript">
<% if Rails.application.secrets.gauges_id %>
  var _gauges = _gauges || [];
  (function() {
    var t   = document.createElement('script');
    t.type  = 'text/javascript';
    t.async = true;
    t.id    = 'gauges-tracker';
    t.setAttribute('data-site-id', '<%= Rails.application.secrets.gauges_id %>');
    t.src = '//secure.gaug.es/track.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(t, s);
  })();
<% end %>

<% if Rails.application.secrets.google_analytics_id %>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '<%= Rails.application.secrets.google_analytics_id %>', 'auto');
  ga('require', 'displayfeatures');
  <% if logged_in? %>
  ga('set', '&uid', '<%= current_user.id %>');
  <% end %>
  ga('send', 'pageview');
<% end %>

<% if Rails.application.secrets.mixpanel_id %>
(function(f,b){if(!b.__SV){var a,e,i,g;window.mixpanel=b;b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.track_charge people.clear_charges people.delete_user".split(" ");
  for(g=0;g<i.length;g++)f(c,i[g]);b._i.push([a,e,d])};b.__SV=1.2;a=f.createElement("script");a.type="text/javascript";a.async=!0;a.src="//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";e=f.getElementsByTagName("script")[0];e.parentNode.insertBefore(a,e)}})(document,window.mixpanel||[]);
mixpanel.init("<%= Rails.application.secrets.mixpanel_id %>");
<% end %>
</script>