config/routes.rb
Rails.application.routes.draw do
  resource  :profile,     only: [ :show, :update ]
  resources :users,       only: [ :index, :show ]
  resources :judges,      only: [ :index, :show, :new, :create ]
  resources :categories,  only: [ :show ]

  resources :problems, only: [ :index, :show, :new, :create ] do
    resources :solutions, only: [ :new, :create, :edit, :update ]
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy', as: :logout
  get '/regwall', to: 'welcome#regwall', as: :regwall
  get '/.well-known/acme-challenge/:id', to: 'welcome#letsencrypt'
  root 'welcome#index'
end

app/models/solution.rb
class Solution < ActiveRecord::Base
  belongs_to :user,    counter_cache: true
  belongs_to :problem, counter_cache: true

  mount_uploader :source_code, SolutionUploader

  validates :user, :problem, :explanation, :source_code, presence: true

  delegate :name, to: :user, prefix: true

  def to_s
    name
  end

  def highlight_lang
    SolutionUploader::EXTENSION_TO_LANG[file_extension]
  end

  def source_code_content
    if source_code.stored_on_s3?
      get_content_from_s3
    else
      File.read(source_code.file.path)
    end
  end

  private

  def get_content_from_s3
    # Download the source code from S3
    Rails.cache.fetch("#{cache_key}/source_content".freeze) do
      HTTParty.get(source_code_url).body
    end
  end

  def file_extension
    @file_extension ||= source_code.file.extension.to_sym
  end
end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController
  before_action :require_login!

  def new
    @solution = problem.solutions.new
  end

  def create
    @solution = current_user.solutions.new(solution_params) { |s| s.problem = problem }
    if @solution.save
      track_event('Solution Created', @solution.as_json(only: [:user_id, :problem_id, :created_at]))
      redirect_to problem, notice: I18n.t('solutions.create.success')
    else
      flash.now[:alert] = I18n.t("solutions.create.error")
      render :new
    end
  end

  def edit
    @solution = current_user.solutions.where(problem: problem).find(params[:id])
  end

  def update
    @solution = current_user.solutions.where(problem: problem).find(params[:id])
    if @solution.update(solution_params)
      track_event('Solution Updated', @solution.as_json(only: [:user_id, :problem_id, :created_at]))
      redirect_to problem, notice: I18n.t('solutions.update.success')
    else
      flash.now[:alert] = I18n.t("solutions.update.error")
    end
  end

  private

  def problem
    @problem ||= Problem.friendly.find(params[:problem_id])
  end

  def solution_params
    params.require(:solution).permit(:explanation, :source_code)
  end
end

app/views/solutions/_form.html.erb
<%= simple_form_for [solution.problem, solution] do |f| %>
  <%= f.input :explanation, as: :text, input_html: { rows: 10 }, placeholder: t('markdown_enabled'), hint: t('.explanation_hint') %>

  <%= f.input :source_code, as: :file, hint: t('.source_code_hint', extensions: SolutionUploader.allowed_extensions.to_sentence) %>

  <%= f.button :submit, data: {"disable-with" => t('application.processing')} %>
<% end %>

app/views/solutions/_solution.html.erb
<% policy = SolutionPolicy.new(current_user, solution) %>
<div class='solution'>
  <header>
    <%= avatar_for(solution.user, size: 64) %>

    <div class='info'>
      <div class='solver'>
        Submitted by <%= link_to solution.user_name, solution.user %> on
        <%= formatted_date(solution.created_at) %>.
      </div>

      <div class='actions'>
        <span class='action show'><%= icon 'eye', t('.show') %></span>

        <% if policy.download? %>
          <span class='action'>
            <%= link_to solution.source_code.url, rel: 'nofollow' do %>
              <%= icon 'cloud-download', t('.download') %>
            <% end %>
          </span>
          <% else %>
          <span class='action disabled'>
            <%= icon 'cloud-download', t('.login_to_download') %>
          </span>
        <% end %>

        <% if policy.update? %>
          <span class='action'>
            <%= link_to edit_problem_solution_url(solution.problem, solution) do %>
              <%= icon 'edit', t('.edit') %>
            <% end %>
          </span>
        <% end %>
      </div>
    </div>
  </header>

  <div class='source'>
    <div class='explanation'><%= markdown(solution.explanation) %></div>
    <pre class='source-code'><%= solution_source(solution) %></pre>
  </div>
</div>

app/views/solutions/edit.html.erb
<h1 class='title'><%= t('.title') %></h1>

<div class='subtitle'>
  <%= t('.subtitle', problem: link_to(@problem.name, @problem), judge: link_to(@problem.judge_name, @problem.judge)).html_safe %>
</div>

<%= render 'form', solution: @solution %>

app/views/solutions/new.html.erb
<h1 class='title'><%= t('.title') %></h1>

<div class='subtitle'>
  <%= t('.subtitle', problem: link_to(@problem.name, @problem), judge: link_to(@problem.judge_name, @problem.judge)).html_safe %>
</div>

<%= render 'form' %>